name: Build App
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "24.11"

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Build backend
        run: npx esbuild src/backend/server.ts --bundle --platform=node --outfile=dist-server/server.js --external:better-sqlite3

      - name: Copy worker
        run: cp src/backend/db.worker.cjs dist-server/

      - name: Build and publish
        run: npx electron-builder -l --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}