name: Build App
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "24.11"

      - run: npm install
      - run: npm run build
      - run: tsc -p tsconfig.server.json
      - run: cp src/backend/db.worker.cjs dist-server/
      - run: ls dist-server/
      - run: npx electron-builder -l
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}